package com.javabuckets.blockshuffle;

import org.bukkit.Bukkit;
import org.bukkit.Material;

import java.util.Arrays;
import java.util.Random;

public class RandomBlockSelector {

    private static Material[] illegalBlocks = {
            Material.AIR,
            Material.BARRIER,
            Material.END_STONE,
            Material.END_PORTAL,
            Material.END_PORTAL_FRAME,
            Material.END_ROD,
            Material.END_CRYSTAL,
            Material.END_GATEWAY,
            Material.END_STONE_BRICK_SLAB,
            Material.END_STONE_BRICK_STAIRS,
            Material.END_STONE_BRICK_WALL,
            Material.END_STONE_BRICKS,
            Material.DRAGON_EGG,
            Material.DRAGON_HEAD,
            Material.DRAGON_WALL_HEAD,
            Material.BEACON,
            Material.INFESTED_CHISELED_STONE_BRICKS,
            Material.INFESTED_COBBLESTONE,
            Material.INFESTED_CRACKED_STONE_BRICKS,
            Material.INFESTED_MOSSY_STONE_BRICKS,
            Material.INFESTED_STONE,
            Material.INFESTED_STONE_BRICKS,
            Material.COMMAND_BLOCK,
            Material.CHORUS_FLOWER,
            Material.CHORUS_FRUIT,
            Material.CHORUS_PLANT,
            Material.CONDUIT,
            Material.CREEPER_HEAD,
            Material.ZOMBIE_HEAD,
            Material.SKELETON_SKULL,
            Material.PLAYER_HEAD,
            Material.WITHER_SKELETON_SKULL,
            Material.CREEPER_WALL_HEAD,
            Material.ZOMBIE_WALL_HEAD,
            Material.SKELETON_WALL_SKULL,
            Material.PLAYER_WALL_HEAD,
            Material.WITHER_SKELETON_WALL_SKULL,
            Material.WITHER_ROSE,
            Material.POTTED_WITHER_ROSE,
            Material.PRISMARINE,
            Material.PRISMARINE_BRICK_SLAB,
            Material.PRISMARINE_BRICK_STAIRS,
            Material.PRISMARINE_BRICKS,
            Material.PRISMARINE_SLAB,
            Material.PRISMARINE_STAIRS,
            Material.PRISMARINE_WALL,
            Material.DARK_PRISMARINE,
            Material.DARK_PRISMARINE_SLAB,
            Material.DARK_PRISMARINE_STAIRS,
            Material.SPONGE,
            Material.WET_SPONGE,
            Material.MYCELIUM,
            Material.NETHERITE_BLOCK,
            Material.STRUCTURE_BLOCK,
            Material.JIGSAW,
            Material.STRUCTURE_VOID,
            Material.BRAIN_CORAL,
            Material.BRAIN_CORAL_BLOCK,
            Material.BRAIN_CORAL_FAN,
            Material.BRAIN_CORAL_WALL_FAN,
            Material.DEAD_BRAIN_CORAL,
            Material.DEAD_BRAIN_CORAL_BLOCK,
            Material.DEAD_BRAIN_CORAL_FAN,
            Material.DEAD_BRAIN_CORAL_WALL_FAN,
            Material.BUBBLE_CORAL,
            Material.BUBBLE_CORAL_BLOCK,
            Material.BUBBLE_CORAL_FAN,
            Material.BUBBLE_CORAL_WALL_FAN,
            Material.DEAD_BUBBLE_CORAL,
            Material.DEAD_BUBBLE_CORAL_BLOCK,
            Material.DEAD_BUBBLE_CORAL_FAN,
            Material.DEAD_BUBBLE_CORAL_WALL_FAN,
            Material.TUBE_CORAL,
            Material.TUBE_CORAL_BLOCK,
            Material.TUBE_CORAL_FAN,
            Material.TUBE_CORAL_WALL_FAN,
            Material.DEAD_TUBE_CORAL,
            Material.DEAD_TUBE_CORAL_BLOCK,
            Material.DEAD_TUBE_CORAL_FAN,
            Material.DEAD_TUBE_CORAL_WALL_FAN,
            Material.HORN_CORAL,
            Material.HORN_CORAL_BLOCK,
            Material.HORN_CORAL_FAN,
            Material.HORN_CORAL_WALL_FAN,
            Material.DEAD_HORN_CORAL,
            Material.DEAD_HORN_CORAL_BLOCK,
            Material.DEAD_HORN_CORAL_FAN,
            Material.DEAD_HORN_CORAL_WALL_FAN,
            Material.FIRE_CORAL,
            Material.FIRE_CORAL_BLOCK,
            Material.FIRE_CORAL_FAN,
            Material.FIRE_CORAL_WALL_FAN,
            Material.DEAD_FIRE_CORAL,
            Material.DEAD_FIRE_CORAL_BLOCK,
            Material.DEAD_FIRE_CORAL_FAN,
            Material.DEAD_FIRE_CORAL_WALL_FAN,
            Material.SHULKER_BOX,
            Material.BLACK_SHULKER_BOX,
            Material.BLUE_SHULKER_BOX,
            Material.BROWN_SHULKER_BOX,
            Material.CYAN_SHULKER_BOX,
            Material.GRAY_SHULKER_BOX,
            Material.GREEN_SHULKER_BOX,
            Material.LIGHT_BLUE_SHULKER_BOX,
            Material.LIGHT_GRAY_SHULKER_BOX,
            Material.LIME_SHULKER_BOX,
            Material.MAGENTA_SHULKER_BOX,
            Material.ORANGE_SHULKER_BOX,
            Material.PINK_SHULKER_BOX,
            Material.PURPLE_SHULKER_BOX,
            Material.RED_SHULKER_BOX,
            Material.WHITE_SHULKER_BOX,
            Material.YELLOW_SHULKER_BOX,
            Material.FROSTED_ICE,
            Material.PISTON_HEAD,
    };

    private static Material[] netherTier = {
            Material.OBSERVER,
            Material.DAYLIGHT_DETECTOR,
            Material.NETHER_BRICK,
            Material.NETHER_BRICK_FENCE,
            Material.NETHER_BRICK_SLAB,
            Material.NETHER_BRICK_STAIRS,
            Material.NETHER_BRICK_WALL,
            Material.NETHER_BRICKS,
            Material.NETHER_GOLD_ORE,
            Material.NETHER_PORTAL,
            Material.NETHER_QUARTZ_ORE,
            Material.NETHER_SPROUTS,
            Material.NETHER_WART,
            Material.NETHER_WART_BLOCK,
            Material.NETHERRACK,
            Material.GLOWSTONE,
            Material.SOUL_CAMPFIRE,
            Material.SOUL_FIRE,
            Material.SOUL_LANTERN,
            Material.SOUL_SAND,
            Material.SOUL_SOIL,
            Material.SOUL_TORCH,
            Material.SOUL_WALL_TORCH,
            Material.BASALT,
            Material.POLISHED_BASALT,
            Material.BLACKSTONE,
            Material.BLACKSTONE_SLAB,
            Material.BLACKSTONE_STAIRS,
            Material.BLACKSTONE_WALL,
            Material.POLISHED_BLACKSTONE,
            Material.POLISHED_BLACKSTONE_SLAB,
            Material.POLISHED_BLACKSTONE_STAIRS,
            Material.POLISHED_BLACKSTONE_WALL,
            Material.POLISHED_BLACKSTONE_BRICKS,
            Material.POLISHED_BLACKSTONE_BRICK_SLAB,
            Material.POLISHED_BLACKSTONE_BRICK_STAIRS,
            Material.POLISHED_BLACKSTONE_BRICK_WALL,
            Material.CHISELED_POLISHED_BLACKSTONE,
            Material.POLISHED_BLACKSTONE_PRESSURE_PLATE,
            Material.POLISHED_BLACKSTONE_BUTTON,
            Material.GILDED_BLACKSTONE,
            Material.SHROOMLIGHT,
            Material.WARPED_STEM,
            Material.WARPED_BUTTON,
            Material.WARPED_DOOR,
            Material.WARPED_FENCE,
            Material.WARPED_FENCE_GATE,
            Material.WARPED_FUNGUS,
            Material.WARPED_HYPHAE,
            Material.WARPED_NYLIUM,
            Material.WARPED_PLANKS,
            Material.WARPED_PRESSURE_PLATE,
            Material.WARPED_ROOTS,
            Material.WARPED_SIGN,
            Material.WARPED_WALL_SIGN,
            Material.WARPED_WART_BLOCK,
            Material.POTTED_WARPED_FUNGUS,
            Material.POTTED_WARPED_ROOTS,
            Material.STRIPPED_WARPED_HYPHAE,
            Material.STRIPPED_WARPED_STEM,
            Material.WARPED_SLAB,
            Material.WARPED_STAIRS,
            Material.WARPED_TRAPDOOR,
            Material.TWISTING_VINES,
            Material.CRIMSON_STEM,
            Material.CRIMSON_BUTTON,
            Material.CRIMSON_DOOR,
            Material.CRIMSON_FENCE,
            Material.CRIMSON_FENCE_GATE,
            Material.CRIMSON_FUNGUS,
            Material.CRIMSON_HYPHAE,
            Material.CRIMSON_NYLIUM,
            Material.CRIMSON_PLANKS,
            Material.CRIMSON_PRESSURE_PLATE,
            Material.CRIMSON_ROOTS,
            Material.CRIMSON_SIGN,
            Material.CRIMSON_WALL_SIGN,
            Material.POTTED_CRIMSON_FUNGUS,
            Material.POTTED_CRIMSON_ROOTS,
            Material.STRIPPED_CRIMSON_HYPHAE,
            Material.STRIPPED_CRIMSON_STEM,
            Material.CRIMSON_SLAB,
            Material.CRIMSON_STAIRS,
            Material.CRIMSON_TRAPDOOR,
            Material.QUARTZ_BLOCK,
            Material.QUARTZ_BRICKS,
            Material.QUARTZ_PILLAR,
            Material.QUARTZ_SLAB,
            Material.QUARTZ_STAIRS,
            Material.SMOOTH_QUARTZ,
            Material.CHISELED_QUARTZ_BLOCK,
            Material.SMOOTH_QUARTZ_SLAB,
            Material.SMOOTH_QUARTZ_STAIRS,
            Material.WEEPING_VINES,
            Material.BONE_BLOCK,
    };

    private static Material[] hardTier = {
            Material.ANVIL,
            Material.CHIPPED_ANVIL,
            Material.DAMAGED_ANVIL,
            Material.ENCHANTING_TABLE,
            Material.ENDER_CHEST,
            Material.DIAMOND_BLOCK,
            Material.EMERALD_BLOCK,
            Material.GOLD_BLOCK,
            Material.LAPIS_BLOCK,
            Material.SLIME_BLOCK,
            Material.HONEY_BLOCK,
            Material.BREWING_STAND,
            Material.ANCIENT_DEBRIS,
            Material.CRYING_OBSIDIAN,
            Material.RESPAWN_ANCHOR,
            Material.LODESTONE,
            Material.SEA_PICKLE,
            Material.STICKY_PISTON,
            Material.ATTACHED_MELON_STEM,
            Material.ATTACHED_PUMPKIN_STEM
    };

    private static Material[] mediumTier = {
            Material.RED_SAND,
            Material.RED_SANDSTONE,
            Material.RED_SANDSTONE_SLAB,
            Material.RED_SANDSTONE_STAIRS,
            Material.RED_SANDSTONE_WALL,
            Material.CHISELED_RED_SANDSTONE,
            Material.CUT_RED_SANDSTONE,
            Material.CUT_RED_SANDSTONE_SLAB,
            Material.SMOOTH_RED_SANDSTONE,
            Material.SMOOTH_RED_SANDSTONE_SLAB,
            Material.SMOOTH_RED_SANDSTONE_STAIRS,
            Material.PODZOL,
            Material.SNOW,
            Material.SNOW_BLOCK,
            Material.ICE,
            Material.PACKED_ICE,
            Material.BLUE_ICE,
            Material.SEA_LANTERN,
            Material.DIAMOND_ORE,
            Material.EMERALD_ORE,
            Material.LAPIS_ORE,
            Material.REDSTONE_ORE,
            Material.REDSTONE_BLOCK,
            Material.BEEHIVE,
            Material.HONEYCOMB_BLOCK,
            Material.BLACK_GLAZED_TERRACOTTA,
            Material.BLUE_GLAZED_TERRACOTTA,
            Material.BROWN_GLAZED_TERRACOTTA,
            Material.CYAN_GLAZED_TERRACOTTA,
            Material.GRAY_GLAZED_TERRACOTTA,
            Material.GREEN_GLAZED_TERRACOTTA,
            Material.LIGHT_BLUE_GLAZED_TERRACOTTA,
            Material.LIGHT_GRAY_GLAZED_TERRACOTTA,
            Material.LIME_GLAZED_TERRACOTTA,
            Material.MAGENTA_GLAZED_TERRACOTTA,
            Material.ORANGE_GLAZED_TERRACOTTA,
            Material.PINK_GLAZED_TERRACOTTA,
            Material.PURPLE_GLAZED_TERRACOTTA,
            Material.RED_GLAZED_TERRACOTTA,
            Material.WHITE_GLAZED_TERRACOTTA,
            Material.YELLOW_GLAZED_TERRACOTTA,
            Material.BLACK_TERRACOTTA,
            Material.BLUE_TERRACOTTA,
            Material.BROWN_TERRACOTTA,
            Material.CYAN_TERRACOTTA,
            Material.GRAY_TERRACOTTA,
            Material.GREEN_TERRACOTTA,
            Material.LIGHT_BLUE_TERRACOTTA,
            Material.LIGHT_GRAY_TERRACOTTA,
            Material.LIME_TERRACOTTA,
            Material.MAGENTA_TERRACOTTA,
            Material.ORANGE_TERRACOTTA,
            Material.PINK_TERRACOTTA,
            Material.PURPLE_TERRACOTTA,
            Material.RED_TERRACOTTA,
            Material.WHITE_TERRACOTTA,
            Material.YELLOW_TERRACOTTA,
            Material.TERRACOTTA,
            Material.REDSTONE_LAMP,
            Material.REDSTONE_TORCH,
            Material.REDSTONE_WALL_TORCH,
            Material.REDSTONE_WIRE,
            Material.REPEATER,
            Material.COMPARATOR,
            Material.TNT,
            Material.TARGET,
            Material.NOTE_BLOCK,
            Material.HOPPER,
            Material.DISPENSER,
            Material.DROPPER,
            Material.TRAPPED_CHEST,
            Material.PISTON,
            Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
            Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
            Material.POWERED_RAIL,
            Material.DETECTOR_RAIL,
            Material.ACTIVATOR_RAIL,
            Material.TRIPWIRE,
            Material.TRIPWIRE_HOOK,
            Material.BROWN_BANNER,
            Material.BROWN_BED,
            Material.BROWN_CARPET,
            Material.BROWN_CONCRETE_POWDER,
            Material.BROWN_CONCRETE,
            Material.BROWN_STAINED_GLASS,
            Material.BROWN_STAINED_GLASS_PANE,
            Material.BROWN_WALL_BANNER,
            Material.POTTED_ACACIA_SAPLING,
            Material.POTTED_BAMBOO,
            Material.POTTED_BROWN_MUSHROOM,
            Material.POTTED_RED_MUSHROOM,
    };

    public static Material getRandomBlock(int score) {
        Material material = null;
        Random random = new Random();
        while (material == null) {
            material = Material.values()[random.nextInt(Material.values().length)];

            if (!(material.isBlock())) {
                material = null;
                continue;
            }

            if (Arrays.asList(illegalBlocks).contains(material)) {
                material = null;
                continue;
            }

            if (Arrays.asList(mediumTier).contains(material)) {
                if (score < 3) {
                    material = null;
                    continue;
                }
            }

            if (Arrays.asList(netherTier).contains(material)) {
                if (score < 7) {
                    material = null;
                    continue;
                }
            }

            if (Arrays.asList(hardTier).contains(material)) {
                if (score < 12) {
                    material = null;
                }
            }
        }
        return material;
    }
}
